# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle: ''
description: ''
keywords:
author: Joan Chen
language: zh-CN
timezone: 'Asia/Shanghai'

# 博客标题
navbar:
  blog_title: Joan Chen's Blog

# 夜间模式
dark_mode:
  enable: true
  default: auto

# 图片懒加载
lazyload:
  enable: true
  loading_img: /img/loading.gif
  onlypost: false
  offset_factor: 2

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://unknown816.github.io
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
# Favicon
favicon: /img/favicon/favicon.ico
apple_touch_icon: /img/favicon/apple-touch-icon.png

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# 首页
index:
  banner_img: /img/bg/home.png
  slogan:
    enable: true
    text: Joan Chen 的个人博客
# 归档
archive:
  banner_img: /img/bg/default.jpg
  banner_img_height: 60
# 分类
category:
  banner_img: /img/bg/default.jpg
  banner_img_height: 60
# 标签
tag:
  banner_img: /img/bg/default.jpg
  banner_img_height: 60
# 关于
about:
  avatar: /img/avatar.png
  banner_img: /img/bg/about.png
  banner_img_height: 60
  name: "Fluid"
  intro: "An elegant theme for Hexo"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/Unknown816', tip: 'GitHub' }
    - { class: 'iconfont icon-wechat-fill', qrcode: '/img/link/wechat.png' }
# 文章页
post:
  banner_img: /img/bg/default.jpg
  default_index_img: /img/post_default.jpg
  banner_img_height: 40
  banner_mask_alpha: 0.3

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fluid

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: 'git'
  repo: 'https://github.com/Unknown816/unknown816.github.io.git'
  branch: 'dev'
  message: 'dev deploy test'
  token: $GITHUB_TOKEN
